Repository SunYerim/ssafyAlgorithmStudy, pull requests merged in 2024-01, with the labels that each got.

#1 [Setting] 프로젝트 폴더 생성
  .gitignore
  yerim/yerimRepo/src/week1/hello.java
Labels: 예림

#3 setting: wonbin 프로젝트 세팅
  .gitignore
  wonbin/.gitignore
  wonbin/java_1/src/java_1/hello_t.java
  wonbin/java_1/src/module-info.java
Labels: 원빈

#5 feat: BOJ10828 스택
  wonbin/java_1/src/week1/BOJ10828_스택.java
Labels: 원빈

#7 fix: 메인 readme 수정
  yerim/yerim.txt
Labels: 예림

#11 SunYerim: 0124 풀이 문제
  yerim/yerimRepo/src/week1/BOJ1012/BOJ1012.java
  yerim/yerimRepo/src/week1/BOJ1012/README.md
  yerim/yerimRepo/src/week1/BOJ1326/BOJ1326.java
  yerim/yerimRepo/src/week1/BOJ1326/README.md
Labels: 예림

#12 [BOJ5972] 택배배송
  yerim/yerimRepo/src/week1/BOJ1326/README.md
  yerim/yerimRepo/src/week1/BOJ5972/BOJ5972.java
  yerim/yerimRepo/src/week1/BOJ5972/README.md
  yerim/yerimRepo/src/week1/hello.java
Labels: 예림

#15 [BOJ2800] 괄호 제거
  yerim/yerimRepo/src/week2/BOJ2800/BOJ2800.java
  yerim/yerimRepo/src/week2/BOJ2800/README.md
Labels: 예림

#16 [BOJ2493]탑
  yerim/yerimRepo/src/week2/BOJ2493/BOJ2493.java
  yerim/yerimRepo/src/week2/BOJ2493/README.md
Labels: 예림

#19 [PGS42587] 프로세스
  yerim/yerimRepo/src/week2/PGS42587/PGS42587.java
  yerim/yerimRepo/src/week2/PGS42587/README.md
Labels: 예림

#24 PS_Week2_Readme update
  heesu/README.md
  heesu/heesu.txt
Labels: 희수

#21 [BOJ22942] 데이터 체커
  yerim/yerimRepo/src/week2/BOJ22942/BOJ22942.java
  yerim/yerimRepo/src/week2/BOJ22942/README.md
  yerim/yerimRepo/src/week2/BOJ22942/img.png
  yerim/yerimRepo/src/week2/PGS42583/PGS42583.java
  yerim/yerimRepo/src/week2/PGS42583/README.md
  yerim/yerimRepo/src/week2/PGS42583/img.png
  yerim/yerimRepo/src/week2/PGS42583/img_1.png
Labels: 예림
